resolver: lts-24.34

allow-newer: true

packages:
- '.'
- packages/hammer/
- packages/sledge/
- packages/queryforest/
- packages/DeUni/
- packages/mcl/
- packages/SubZero/
- packages/VTK/
- packages/linear-vect/

extra-deps:
- mersenne-random-pure64-0.2.0.5@sha256:8f98b614aeed639713f01155e912aa6ad117073d0863f5783d1577764fd85b1a,2426

nix:
  enable: false
