resolver: lts-5.2

packages:
- '.'
- packages/hammer/
- packages/sledge/
- packages/queryforest/
- packages/DeUni/
- packages/mcl/
- packages/SubZero/
- packages/VTK/
- packages/linear-vect/

extra-deps: []
flags: {}
extra-package-dbs: []
