name:          VirMat
version:       0.4.1
license:       GPL-3
license-file:  LICENSE
author:        Edgar Gomes de Araujo
maintainer:    Edgar Gomes de Araujo <talktoedgar@gmail.com>
homepage:
stability:     Experimental
synopsis:      3D Microstructure Generator
description:   Creates virtual microstructure in 3 dimesions.
cabal-version: >=1.8
build-type:    Simple
category:      Data, Math

flag generator
  description: Build the exectable using command line.
  default:     True

executable virmatgen
  hs-source-dirs: src
  main-is:        Main.hs
  ghc-options:    -Wall -O3 -threaded -rtsopts -auto-all -caf-all
  build-depends:
      base                    >=4    && <5
    , containers              >=0.5
    , DeUni                   >=0.3
    , hammer                  >=0.3
    , linear-vect             >=0.2
    , mersenne-random-pure64  >=0.2
    , mtl                     >=2.1
    , optparse-applicative    >=0.7
    , random                  >=1.2
    , random-fu               >=0.2
    , sledge                  >=0.3
    , SubZero                 >=0.1
    , transformers            >=0.3
    , unordered-containers    >=0.2
    , vector                  >=0.10
    , VirMat

  if flag(generator)
    buildable: True

  else
    buildable: False

library
  ghc-options:     -Wall -fwarn-tabs -funbox-strict-fields -O2
  hs-source-dirs:  src
  build-depends:
      base                    >=4    && <5
    , containers              >=0.5
    , DeUni                   >=0.3
    , hammer                  >=0.3
    , linear-vect             >=0.2
    , mersenne-random-pure64  >=0.2
    , mtl                     >=2.1
    , random                  >=1.2
    , random-fu               >=0.2
    , sledge                  >=0.3
    , SubZero                 >=0.1
    , transformers            >=0.3
    , unordered-containers    >=0.2
    , vector                  >=0.10

  exposed-modules:
    VirMat.Core.FlexMicro
    VirMat.Core.Packer
    VirMat.Core.Sampling
    VirMat.Core.VoronoiMicro
    VirMat.Distributions.GrainSize.GrainDistributionGenerator
    VirMat.Distributions.GrainSize.GrainQuery
    VirMat.Distributions.Texture.ODFSampling
    VirMat.IO.Export.ANG.RasterEngine
    VirMat.IO.Export.Types
    VirMat.IO.Import.Types
    VirMat.PhaseTrans
    VirMat.Run2D
    VirMat.Run3D
    VirMat.Types
